---
- name: Configure K3s Controller
  hosts: controller
  tasks:
    - name: Configure K3s Controller
      ansible.builtin.shell:
        cmd: |
          curl -sfL https://get.k3s.io | sh -s - --write-kubeconfig-mode 644
          sudo cat /var/lib/rancher/k3s/server/node-token >> ~/k3s_token
      register: result

    - name: Results
      ansible.builtin.debug:
        var: result.stdout_lines
