---
- name: Configure K3s Workers
  hosts: workers
  vars:
    controller_hostname: kubectl.code-get.com
  tasks:
    - name: Configure K3s worker
      ansible.builtin.shell:
        cmd: |
         server_address={{ controller_hostname }}
         scp -i ~/key.pem -o StrictHostKeyChecking=accept-new "$server_address:k3s_token" .
         k3s_token="$(cat ~/k3s_token)"
         curl -sfL https://get.k3s.io | K3S_URL="https://$server_address:6443" K3S_TOKEN="$k3s_token" sh -
      register: result

    - name: Results
      ansible.builtin.debug:
        var: result.stdout_lines
